# Generated by Django 4.2.30 on 2026-05-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('units', models.PositiveSmallIntegerField()),
                ('instructor', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
